//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.17929
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModernUIApp1.Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LinkResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LinkResources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ModernUIApp1.Resources.LinkResources", typeof(LinkResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à annotations.
        /// </summary>
        internal static string Annotations {
            get {
                return ResourceManager.GetString("Annotations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à email.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à end.
        /// </summary>
        internal static string End {
            get {
                return ResourceManager.GetString("End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à firstname.
        /// </summary>
        internal static string Firstname {
            get {
                return ResourceManager.GetString("Firstname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à height.
        /// </summary>
        internal static string Height {
            get {
                return ResourceManager.GetString("Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à id_annotation_page_table.
        /// </summary>
        internal static string IdAnnotationPageTable {
            get {
                return ResourceManager.GetString("IdAnnotationPageTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à id_annotation_sheet.
        /// </summary>
        internal static string IdAnnotationSheet {
            get {
                return ResourceManager.GetString("IdAnnotationSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à id_file.
        /// </summary>
        internal static string IdFile {
            get {
                return ResourceManager.GetString("IdFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à id_folder.
        /// </summary>
        internal static string IdFolder {
            get {
                return ResourceManager.GetString("IdFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à id_icon.
        /// </summary>
        internal static string IdIcon {
            get {
                return ResourceManager.GetString("IdIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à id_number.
        /// </summary>
        internal static string IdNumber {
            get {
                return ResourceManager.GetString("IdNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à id_page_table.
        /// </summary>
        internal static string IdPageTable {
            get {
                return ResourceManager.GetString("IdPageTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à id_parent_folder.
        /// </summary>
        internal static string IdParentFolder {
            get {
                return ResourceManager.GetString("IdParentFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à id_register.
        /// </summary>
        internal static string IdRegister {
            get {
                return ResourceManager.GetString("IdRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à id_session.
        /// </summary>
        internal static string IdSession {
            get {
                return ResourceManager.GetString("IdSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à id_sheet.
        /// </summary>
        internal static string IdSheet {
            get {
                return ResourceManager.GetString("IdSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à id_shortcut.
        /// </summary>
        internal static string IdShortcut {
            get {
                return ResourceManager.GetString("IdShortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à id_type.
        /// </summary>
        internal static string IdType {
            get {
                return ResourceManager.GetString("IdType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à image_src.
        /// </summary>
        internal static string ImageSource {
            get {
                return ResourceManager.GetString("ImageSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à item.
        /// </summary>
        internal static string Item {
            get {
                return ResourceManager.GetString("Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à job.
        /// </summary>
        internal static string Job {
            get {
                return ResourceManager.GetString("Job", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à lastname.
        /// </summary>
        internal static string Lastname {
            get {
                return ResourceManager.GetString("Lastname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à annotator/add_or_update_annotation_sheet/session_id/id_annotation_sheet/id_sheet/id_type/posx/posy/text.
        /// </summary>
        internal static string LinkAddOrUpdateAnnotationSheet {
            get {
                return ResourceManager.GetString("LinkAddOrUpdateAnnotationSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à shortcut/add_shortcut/session_id/id_type/text/id_icon.
        /// </summary>
        internal static string LinkAddShortcut {
            get {
                return ResourceManager.GetString("LinkAddShortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à annotator/annotate_sheet/session_id/id_sheet/id_type/posx/posy/text.
        /// </summary>
        internal static string LinkAnnotateSheet {
            get {
                return ResourceManager.GetString("LinkAnnotateSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à annotator/annotate_table/session_id/id_page_table/posx/posy/height/width/number.
        /// </summary>
        internal static string LinkAnnotateTable {
            get {
                return ResourceManager.GetString("LinkAnnotateTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à bookmark/get_list/session_id.
        /// </summary>
        internal static string LinkBookmarkGetRoot {
            get {
                return ResourceManager.GetString("LinkBookmarkGetRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à bookmark/create_bookmark_file/session_id/id_parent_folder/id_sheet/name.
        /// </summary>
        internal static string LinkBookmarkNewFile {
            get {
                return ResourceManager.GetString("LinkBookmarkNewFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à bookmark/create_bookmark_folder/session_id/id_parent_folder/name.
        /// </summary>
        internal static string LinkBookmarkNewFolder {
            get {
                return ResourceManager.GetString("LinkBookmarkNewFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à bookmark/remove_bookmark_file/session_id/id_file.
        /// </summary>
        internal static string LinkBookmarkRemoveFile {
            get {
                return ResourceManager.GetString("LinkBookmarkRemoveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à bookmark/remove_bookmark_folder/session_id/id_folder.
        /// </summary>
        internal static string LinkBookmarkRemoveFolder {
            get {
                return ResourceManager.GetString("LinkBookmarkRemoveFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à bookmark/rename_bookmark_file/session_id/id_file/new_name.
        /// </summary>
        internal static string LinkBookmarkRenameFile {
            get {
                return ResourceManager.GetString("LinkBookmarkRenameFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à bookmark/rename_bookmark_folder/session_id/id_folder/new_name.
        /// </summary>
        internal static string LinkBookmarkRenameFolder {
            get {
                return ResourceManager.GetString("LinkBookmarkRenameFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à bookmark/update_parent_bookmark_file/session_id/id_file/id_parent_folder.
        /// </summary>
        internal static string LinkBookmarkUpdateFileParent {
            get {
                return ResourceManager.GetString("LinkBookmarkUpdateFileParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à bookmark/update_parent_bookmark_folder/session_id/id_folder/id_parent_folder.
        /// </summary>
        internal static string LinkBookmarkUpdateFolderParent {
            get {
                return ResourceManager.GetString("LinkBookmarkUpdateFolderParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à annotator/delete_annotation_sheet/session_id/id_annotation_sheet.
        /// </summary>
        internal static string LinkDeleteAnnotationSheet {
            get {
                return ResourceManager.GetString("LinkDeleteAnnotationSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à annotator/delete_annotation_page_table/session_id/id_annotation_page_table.
        /// </summary>
        internal static string LinkDeleteAnnotationTable {
            get {
                return ResourceManager.GetString("LinkDeleteAnnotationTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à shortcut/delete_shortcut/id_shortcut.
        /// </summary>
        internal static string LinkDeleteShortcut {
            get {
                return ResourceManager.GetString("LinkDeleteShortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à shortcut/get_all_shortcut/session_id.
        /// </summary>
        internal static string LinkGetAllShortcut {
            get {
                return ResourceManager.GetString("LinkGetAllShortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à annotator/get_annotation_sheet/session_id/id_sheet.
        /// </summary>
        internal static string LinkGetAnnotSheet {
            get {
                return ResourceManager.GetString("LinkGetAnnotSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à annotator/get_annotation_table/session_id/id_page_table.
        /// </summary>
        internal static string LinkGetAnnotTable {
            get {
                return ResourceManager.GetString("LinkGetAnnotTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à browser/get_page_table/idPageTable/idUser/page.
        /// </summary>
        internal static string LinkGetPageTable {
            get {
                return ResourceManager.GetString("LinkGetPageTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à toComplete.
        /// </summary>
        internal static string LinkGetRegister {
            get {
                return ResourceManager.GetString("LinkGetRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à browser/get_sheet/idRegister/idUser/matriculeNumber.
        /// </summary>
        internal static string LinkGetSheet {
            get {
                return ResourceManager.GetString("LinkGetSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à browser/get_sheet_by_id/id_sheet/.
        /// </summary>
        internal static string LinkGetSheetById {
            get {
                return ResourceManager.GetString("LinkGetSheetById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à browser/get_sheets/idRegister/idUser/start/end.
        /// </summary>
        internal static string LinkGetSheets {
            get {
                return ResourceManager.GetString("LinkGetSheets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à browser/get_table/idRegister/idUser.
        /// </summary>
        internal static string LinkGetTable {
            get {
                return ResourceManager.GetString("LinkGetTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à annotator/get_types//.
        /// </summary>
        internal static string LinkGetTypes {
            get {
                return ResourceManager.GetString("LinkGetTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à authentificator/login/email/password.
        /// </summary>
        internal static string LinkLogin {
            get {
                return ResourceManager.GetString("LinkLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à authentificator/logout/session_id.
        /// </summary>
        internal static string LinkLogout {
            get {
                return ResourceManager.GetString("LinkLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à browser/preload_sheets/id_sheet.
        /// </summary>
        internal static string LinkPreloadSheets {
            get {
                return ResourceManager.GetString("LinkPreloadSheets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à file/print_file/path.
        /// </summary>
        internal static string LinkPrintFile {
            get {
                return ResourceManager.GetString("LinkPrintFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à authentificator/register/email/password.
        /// </summary>
        internal static string LinkRegister {
            get {
                return ResourceManager.GetString("LinkRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à finder/search_sheet/year/location/firstname/lastname/job/regiment/other.
        /// </summary>
        internal static string LinkSearchSheet {
            get {
                return ResourceManager.GetString("LinkSearchSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à finder/search_table/year/location.
        /// </summary>
        internal static string LinkSearchTable {
            get {
                return ResourceManager.GetString("LinkSearchTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à annotator/update_annotation_sheet/session_id/id_annotation_sheet/id_type/posx/posy/text.
        /// </summary>
        internal static string LinkUpdateAnnotationSheet {
            get {
                return ResourceManager.GetString("LinkUpdateAnnotationSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à annotator/update_annotation_table/session_id/id_annotation_page_table/posx/posy/height/width/number.
        /// </summary>
        internal static string LinkUpdateAnnotationTable {
            get {
                return ResourceManager.GetString("LinkUpdateAnnotationTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à location.
        /// </summary>
        internal static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à message.
        /// </summary>
        internal static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à connected.
        /// </summary>
        internal static string MsgConnected {
            get {
                return ResourceManager.GetString("MsgConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ok.
        /// </summary>
        internal static string MsgOk {
            get {
                return ResourceManager.GetString("MsgOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à registered.
        /// </summary>
        internal static string MsgRegistered {
            get {
                return ResourceManager.GetString("MsgRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à null.
        /// </summary>
        internal static string MsNull {
            get {
                return ResourceManager.GetString("MsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à new_name.
        /// </summary>
        internal static string NewName {
            get {
                return ResourceManager.GetString("NewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à number.
        /// </summary>
        internal static string Number {
            get {
                return ResourceManager.GetString("Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à other.
        /// </summary>
        internal static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à page.
        /// </summary>
        internal static string Page {
            get {
                return ResourceManager.GetString("Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à path.
        /// </summary>
        internal static string Path {
            get {
                return ResourceManager.GetString("Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à regiment.
        /// </summary>
        internal static string Regiment {
            get {
                return ResourceManager.GetString("Regiment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à register.
        /// </summary>
        internal static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à result_id.
        /// </summary>
        internal static string ResultId {
            get {
                return ResourceManager.GetString("ResultId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à session_id.
        /// </summary>
        internal static string SessionId {
            get {
                return ResourceManager.GetString("SessionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à size.
        /// </summary>
        internal static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à start.
        /// </summary>
        internal static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à text.
        /// </summary>
        internal static string Text {
            get {
                return ResourceManager.GetString("Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à type.
        /// </summary>
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à vol.
        /// </summary>
        internal static string Volume {
            get {
                return ResourceManager.GetString("Volume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à width.
        /// </summary>
        internal static string Width {
            get {
                return ResourceManager.GetString("Width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à posx.
        /// </summary>
        internal static string X {
            get {
                return ResourceManager.GetString("X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à posy.
        /// </summary>
        internal static string Y {
            get {
                return ResourceManager.GetString("Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à year.
        /// </summary>
        internal static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
    }
}
